[project]
name = "extra-tables"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pypath-omnipath",
]

[tool.uv.sources]
pypath-omnipath = { git = "https://github.com/saezlab/pypath.git" }
